### ISSUE TITLE
Exception thrown after animation finishes

### ISSUE THREAD

**Issue by ealmiladi** [heyman333/react-native-animated-numbers#10]
![image](https://user-images.githubusercontent.com/27777704/96354694-10a49c80-109f-11eb-9a04-c4e19cb35119.png)

```
useEffect(() => {
        const timer = setTimeout(() => {
            setAnimateToNumber(parseFloat(user.balance || 0));
        }, 200);
        return () => clearTimeout(timer);
    }, [user.balance]);

                        <AnimatedNumbers
                            includeComma
                            animateToNumber={animateToNumber}
                            fontStyle={{fontSize: 24, fontWeight: 'bold', color: getColor('gray-700')}}
                        />
```

The issue occurs intermittently. My version is 0.2.0.

**Comment by heyman333** [comment]
@ealmiladi Thank you your report. I will check your code and fix it as soon as possible!

**Comment by ealmiladi** [comment]
@heyman333 No problem. FYI, this one may be hard to replicate. After installing 0.1.1 and then reinstalling 0.2.0, I was no longer able to replicate this issue. Very odd. I just hope you don't go down the rabbit hole trying to fix this one! I appreciate the prompt response!

**Comment by heyman333** [comment]
@ealmiladi Your're welcome, I won't close this issue. If you show this error again, just report issue again

**Comment by avinashlng1080** [comment]
I'm having the same issue.  I have a long lists of messages and each message renders an AnimatedNumber component.  @heyman333  and @ealmiladi  can you please share what you found?
