### ISSUE TITLE
Can't use numbers with dots

### ISSUE THREAD

**Issue by aveWorld** [heyman333/react-native-animated-numbers#11]
It crashes when I'm trying to use numbers with dots

![crash2](https://user-images.githubusercontent.com/46648541/106726115-b4946280-6612-11eb-9e91-853d175de5b0.jpg)

![crash1](https://user-images.githubusercontent.com/46648541/106726140-b9f1ad00-6612-11eb-9959-2e2ea64caeec.jpg)

**Comment by heyman333** [comment]
@aveWorld  So far, it only support integers😅
